import { BrowserTarget, CapabilityRequestContext } from '../../shared/control-plane-contracts';
import { BrowserControlPort } from './browser-control-port';
import { CapabilityCatalogue } from './capability-catalogue';

export function registerBrowserCapabilities(catalogue: CapabilityCatalogue, browser: BrowserControlPort): void {
  // 1. Standard canonical capabilities
  catalogue.register({ name: 'browser.list-tabs', description: 'List Chromium tabs without selecting an active tab', risk: 'read', inputSchema: { type: 'object' }, execute: (_params, context) => browser.listTabs({ target: context.browserTarget }) });
  catalogue.register({ name: 'browser.open-tab', description: 'Open a new Chromium browser tab', risk: 'write', inputSchema: { type: 'object', properties: { url: { type: 'string' } } }, execute: (params: { url?: string }) => browser.openTab(params.url) });
  catalogue.register({ name: 'browser.close-tab', description: 'Close a Chromium browser tab by ID', risk: 'write', inputSchema: { type: 'object', properties: { tabId: { type: 'string' } }, required: ['tabId'] }, execute: (params: { tabId: string }) => browser.closeTab(params.tabId) });
  catalogue.register({ name: 'browser.switch-tab', description: 'Switch to a Chromium browser tab by ID', risk: 'write', inputSchema: { type: 'object', properties: { tabId: { type: 'string' } }, required: ['tabId'] }, execute: (params: { tabId: string }) => browser.switchTab(params.tabId) });
  catalogue.register({ name: 'browser.navigate', description: 'Navigate the explicitly bound Chromium tab (or specified tabId)', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { url: { type: 'string' }, tabId: { type: 'string' } }, required: ['url'] }, execute: (params: { url: string; tabId?: string }, context) => browser.navigate(context.browserTarget as BrowserTarget, params.url, params.tabId) });
  catalogue.register({ name: 'browser.reload', description: 'Reload the explicitly bound Chromium tab (or specified tabId)', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { tabId: { type: 'string' } } }, execute: (params: { tabId?: string }, context) => browser.reload(context.browserTarget as BrowserTarget, params.tabId) });
  catalogue.register({ name: 'browser.dom', description: 'Capture bounded DOM evidence for the explicitly bound tab (or specified tabId)', risk: 'read', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { selector: { type: 'string' }, tabId: { type: 'string' } } }, execute: async (params: { selector?: string; tabId?: string }, context) => browser.dom(context.browserTarget as BrowserTarget, context.runId || 'run-unbound', context.attemptId || 'attempt-unbound', params.selector, params.tabId) });
  catalogue.register({ name: 'browser.screenshot', description: 'Capture bounded screenshot evidence for the explicitly bound tab (or specified tabId)', risk: 'read', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { tabId: { type: 'string' } } }, execute: async (params: { tabId?: string }, context) => browser.screenshot(context.browserTarget as BrowserTarget, context.runId || 'run-unbound', context.attemptId || 'attempt-unbound', params.tabId) });
  catalogue.register({ name: 'browser.eval', description: 'Evaluate JavaScript only with an explicit eval grant', risk: 'eval', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { expression: { type: 'string' } }, required: ['expression'] }, execute: (params: { expression: string }, context) => browser.eval(context.browserTarget as BrowserTarget, params.expression) });
  catalogue.register({ name: 'browser.diagnostics', description: 'Get tab console logs and network failures', risk: 'read', inputSchema: { type: 'object', properties: { tabId: { type: 'string' }, level: { type: 'number' } } }, execute: (params: { tabId?: string; level?: number | string }) => browser.diagnostics(params.tabId, params.level) });
  catalogue.register({ name: 'browser.responsive-check', description: 'Run responsive layout verification on a tab', risk: 'read', inputSchema: { type: 'object', properties: { tabId: { type: 'string' } }, required: ['tabId'] }, execute: (params: { tabId: string }) => browser.responsiveCheck(params.tabId) });
  catalogue.register({ name: 'browser.agent-move', description: 'Move agent virtual cursor to an element or coordinate', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { selector: { type: 'string' }, x: { type: 'number' }, y: { type: 'number' }, label: { type: 'string' }, tabId: { type: 'string' } } }, execute: (params: { selector?: string; x?: number; y?: number; label?: string; tabId?: string }, context) => browser.agentMove(params, context.browserTarget) });
  catalogue.register({ name: 'browser.agent-click', description: 'Click an element or coordinate using agent cursor', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { selector: { type: 'string' }, ref: { type: 'string' }, x: { type: 'number' }, y: { type: 'number' }, label: { type: 'string' }, tabId: { type: 'string' } } }, execute: (params: { selector?: string; ref?: string; x?: number; y?: number; label?: string; tabId?: string }, context) => browser.agentClick(params, context.browserTarget) });
  catalogue.register({ name: 'browser.agent-type', description: 'Type text into an input element using agent cursor', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { selector: { type: 'string' }, text: { type: 'string' }, clear: { type: 'boolean' }, tabId: { type: 'string' } }, required: ['selector', 'text'] }, execute: (params: { selector: string; text: string; clear?: boolean; tabId?: string }, context) => browser.agentType(params, context.browserTarget) });
  catalogue.register({ name: 'browser.keyboard-press', description: 'Send native key press (Enter, Escape, Tab, Backspace, Arrow keys, etc.) or combination (Ctrl+A) to the active tab', risk: 'write', inputSchema: { type: 'object', properties: { key: { type: 'string' }, modifiers: { type: 'array', items: { type: 'string' } }, tabId: { type: 'string' } }, required: ['key'] }, execute: (params: { key: string; modifiers?: string[]; tabId?: string }, context) => browser.keyboardPress(params, context.browserTarget) });
  catalogue.register({ name: 'browser.agent-scroll', description: 'Scroll page or element using agent cursor', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { deltaY: { type: 'number' }, selector: { type: 'string' }, tabId: { type: 'string' } } }, execute: (params: { deltaY?: number; selector?: string; tabId?: string }, context) => browser.agentScroll(params, context.browserTarget) });
  catalogue.register({ name: 'browser.agent-hover', description: 'Hover an element or coordinate using agent cursor', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { selector: { type: 'string' }, x: { type: 'number' }, y: { type: 'number' }, label: { type: 'string' }, tabId: { type: 'string' } } }, execute: (params: { selector?: string; x?: number; y?: number; label?: string; tabId?: string }, context) => browser.agentHover(params, context.browserTarget) });
  catalogue.register({ name: 'browser.agent-highlight', description: 'Highlight an element on page', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { selector: { type: 'string' }, label: { type: 'string' }, tabId: { type: 'string' } }, required: ['selector'] }, execute: (params: { selector: string; label?: string; tabId?: string }, context) => browser.agentHighlight(params, context.browserTarget) });
  catalogue.register({ name: 'browser.agent-clear', description: 'Clear all agent visual cursor overlays', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { tabId: { type: 'string' } } }, execute: (params: { tabId?: string }, context) => browser.agentClear(params.tabId, context.browserTarget) });
  catalogue.register({ name: 'browser.agent-snapshot', description: 'Capture agent visual snapshot tree', risk: 'read', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { tabId: { type: 'string' } } }, execute: (params: { tabId?: string }, context) => browser.agentSnapshot(params.tabId, context.browserTarget) });
  catalogue.register({ name: 'browser.agent-trajectory', description: 'Execute a continuous multi-step Bézier mouse trajectory and action sequence', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { steps: { type: 'array', items: { type: 'object' } }, speed: { type: 'string', enum: ['fast', 'natural', 'slow'] }, smoothScroll: { type: 'boolean' }, tabId: { type: 'string' } }, required: ['steps'] }, execute: (params: { steps: Array<Record<string, unknown>>; speed?: 'fast' | 'natural' | 'slow'; smoothScroll?: boolean; tabId?: string }, context) => browser.agentTrajectory(params, context.browserTarget) });
  catalogue.register({ name: 'browser.set-viewport', description: 'Set browser responsive viewport dimensions (width, height, mobile emulation, DPR)', risk: 'write', inputSchema: { type: 'object', properties: { width: { type: 'number' }, height: { type: 'number' }, mobile: { type: 'boolean' }, deviceScaleFactor: { type: 'number' }, tabId: { type: 'string' } }, required: ['width', 'height'] }, execute: (params: { width: number; height: number; mobile?: boolean; deviceScaleFactor?: number; tabId?: string }, context) => browser.setViewport(params, context.browserTarget) });
  catalogue.register({ name: 'browser.set-device-preset', description: 'Emulate a real device preset (iPhone, iPad, Galaxy, Pixel, MacBook, 4K, Desktop) on a tab', risk: 'write', inputSchema: { type: 'object', properties: { presetId: { type: 'string' }, tabId: { type: 'string' } }, required: ['presetId'] }, execute: (params: { presetId: string; tabId?: string }, context) => browser.setDevicePreset(params, context.browserTarget) });
  catalogue.register({ name: 'browser.list-device-presets', description: 'List all available responsive device presets with their resolutions and categories', risk: 'read', inputSchema: { type: 'object' }, execute: () => browser.listDevicePresets() });
  catalogue.register({ name: 'browser.set-zoom', description: 'Set zoom factor for a Chromium tab (0.25 to 5.0)', risk: 'write', inputSchema: { type: 'object', properties: { zoomFactor: { type: 'number', minimum: 0.25, maximum: 5.0, description: 'Zoom factor between 0.25 and 5.0' }, tabId: { type: 'string' } }, required: ['zoomFactor'] }, execute: (params: { zoomFactor: number; tabId?: string }, context) => browser.setZoom(params, context.browserTarget) });
  catalogue.register({ name: 'browser.toggle-inspect', description: 'Toggle native element inspection overlay', risk: 'write', inputSchema: { type: 'object' }, execute: () => browser.toggleInspect() });
  // 2. Compatibility aliases for MCP & Bridge protocols
  catalogue.register({ name: 'antifan_list_tabs', description: 'Alias for browser.list-tabs', risk: 'read', inputSchema: { type: 'object' }, execute: (_params, context) => browser.listTabs({ target: context.browserTarget }) });
  catalogue.register({ name: 'antifan_open_tab', description: 'Alias for browser.open-tab', risk: 'write', inputSchema: { type: 'object', properties: { url: { type: 'string' } } }, execute: (params: { url?: string }) => browser.openTab(params.url) });
  catalogue.register({ name: 'antifan_close_tab', description: 'Alias for browser.close-tab', risk: 'write', inputSchema: { type: 'object', properties: { tabId: { type: 'string' } }, required: ['tabId'] }, execute: (params: { tabId: string }) => browser.closeTab(params.tabId) });
  catalogue.register({ name: 'antifan_switch_tab', description: 'Alias for browser.switch-tab', risk: 'write', inputSchema: { type: 'object', properties: { tabId: { type: 'string' } }, required: ['tabId'] }, execute: (params: { tabId: string }) => browser.switchTab(params.tabId) });
  catalogue.register({ name: 'antifan_navigate', description: 'Alias for browser.navigate', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { url: { type: 'string' }, tabId: { type: 'string' } }, required: ['url'] }, execute: (params: { url: string; tabId?: string }, context) => browser.navigate(context.browserTarget as BrowserTarget, params.url, params.tabId) });
  catalogue.register({ name: 'antifan_reload', description: 'Alias for browser.reload', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { tabId: { type: 'string' } } }, execute: (params: { tabId?: string }, context) => browser.reload(context.browserTarget as BrowserTarget, params.tabId) });
  catalogue.register({ name: 'antifan_get_dom', description: 'Alias for browser.dom', risk: 'read', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { selector: { type: 'string' }, tabId: { type: 'string' } } }, execute: async (params: { selector?: string; tabId?: string }, context) => browser.dom(context.browserTarget as BrowserTarget, context.runId || 'run-unbound', context.attemptId || 'attempt-unbound', params.selector, params.tabId) });
  catalogue.register({ name: 'antifan_screenshot', description: 'Alias for browser.screenshot', risk: 'read', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { tabId: { type: 'string' } } }, execute: async (params: { tabId?: string }, context) => browser.screenshot(context.browserTarget as BrowserTarget, context.runId || 'run-unbound', context.attemptId || 'attempt-unbound', params.tabId) });
  catalogue.register({ name: 'antifan_toggle_inspect', description: 'Alias for browser.toggle-inspect', risk: 'write', inputSchema: { type: 'object', properties: { tabId: { type: 'string' } } }, execute: () => browser.toggleInspect() });
  catalogue.register({ name: 'antifan_agent_snapshot', description: 'Alias for browser.agent-snapshot', risk: 'read', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { tabId: { type: 'string' } } }, execute: (params: { tabId?: string }, context) => browser.agentSnapshot(params.tabId, context.browserTarget) });
  catalogue.register({ name: 'antifan_agent_click', description: 'Alias for browser.agent-click', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { selector: { type: 'string' }, ref: { type: 'string' }, x: { type: 'number' }, y: { type: 'number' }, label: { type: 'string' }, tabId: { type: 'string' } } }, execute: (params: { selector?: string; ref?: string; x?: number; y?: number; label?: string; tabId?: string }, context) => browser.agentClick(params, context.browserTarget) });
  catalogue.register({ name: 'antifan_agent_type', description: 'Alias for browser.agent-type', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { selector: { type: 'string' }, text: { type: 'string' }, clear: { type: 'boolean' }, tabId: { type: 'string' } }, required: ['selector', 'text'] }, execute: (params: { selector: string; text: string; clear?: boolean; tabId?: string }, context) => browser.agentType(params, context.browserTarget) });
  catalogue.register({ name: 'antifan_keyboard_press', description: 'Alias for browser.keyboard-press', risk: 'write', inputSchema: { type: 'object', properties: { key: { type: 'string' }, modifiers: { type: 'array', items: { type: 'string' } }, tabId: { type: 'string' } }, required: ['key'] }, execute: (params: { key: string; modifiers?: string[]; tabId?: string }, context) => browser.keyboardPress(params, context.browserTarget) });
  catalogue.register({ name: 'antifan_agent_scroll', description: 'Alias for browser.agent-scroll', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { deltaY: { type: 'number' }, selector: { type: 'string' }, tabId: { type: 'string' } } }, execute: (params: { deltaY?: number; selector?: string; tabId?: string }, context) => browser.agentScroll(params, context.browserTarget) });
  catalogue.register({ name: 'antifan_agent_hover', description: 'Alias for browser.agent-hover', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { selector: { type: 'string' }, x: { type: 'number' }, y: { type: 'number' }, label: { type: 'string' }, tabId: { type: 'string' } } }, execute: (params: { selector?: string; x?: number; y?: number; label?: string; tabId?: string }, context) => browser.agentHover(params, context.browserTarget) });
  catalogue.register({ name: 'antifan_agent_highlight', description: 'Alias for browser.agent-highlight', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { selector: { type: 'string' }, label: { type: 'string' }, tabId: { type: 'string' } }, required: ['selector'] }, execute: (params: { selector: string; label?: string; tabId?: string }, context) => browser.agentHighlight(params, context.browserTarget) });
  catalogue.register({ name: 'antifan_agent_clear', description: 'Alias for browser.agent-clear', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { tabId: { type: 'string' } } }, execute: (params: { tabId?: string }, context) => browser.agentClear(params.tabId, context.browserTarget) });
  catalogue.register({ name: 'antifan_agent_trajectory', description: 'Alias for browser.agent-trajectory', risk: 'write', requiresBrowserTarget: true, inputSchema: { type: 'object', properties: { steps: { type: 'array', items: { type: 'object' } }, speed: { type: 'string', enum: ['fast', 'natural', 'slow'] }, smoothScroll: { type: 'boolean' }, tabId: { type: 'string' } }, required: ['steps'] }, execute: (params: { steps: Array<Record<string, unknown>>; speed?: 'fast' | 'natural' | 'slow'; smoothScroll?: boolean; tabId?: string }, context) => browser.agentTrajectory(params, context.browserTarget) });
  catalogue.register({ name: 'antifan_console_messages', description: 'Alias for browser.diagnostics', risk: 'read', inputSchema: { type: 'object', properties: { tabId: { type: 'string' }, level: { type: 'number' } } }, execute: (params: { tabId?: string; level?: number | string }) => browser.diagnostics(params.tabId, params.level) });
  catalogue.register({ name: 'antifan_network_failures', description: 'Alias for browser.diagnostics', risk: 'read', inputSchema: { type: 'object', properties: { tabId: { type: 'string' } } }, execute: (params: { tabId?: string }) => browser.diagnostics(params.tabId) });
  catalogue.register({ name: 'antifan_responsive_check', description: 'Alias for browser.responsive-check', risk: 'read', inputSchema: { type: 'object', properties: { tabId: { type: 'string' } }, required: ['tabId'] }, execute: (params: { tabId: string }) => browser.responsiveCheck(params.tabId) });
  catalogue.register({ name: 'antifan_set_viewport', description: 'Alias for browser.set-viewport', risk: 'write', inputSchema: { type: 'object', properties: { width: { type: 'number' }, height: { type: 'number' }, mobile: { type: 'boolean' }, deviceScaleFactor: { type: 'number' }, tabId: { type: 'string' } }, required: ['width', 'height'] }, execute: (params: { width: number; height: number; mobile?: boolean; deviceScaleFactor?: number; tabId?: string }, context) => browser.setViewport(params, context.browserTarget) });
  catalogue.register({ name: 'antifan_set_device_preset', description: 'Alias for browser.set-device-preset', risk: 'write', inputSchema: { type: 'object', properties: { presetId: { type: 'string' }, tabId: { type: 'string' } }, required: ['presetId'] }, execute: (params: { presetId: string; tabId?: string }, context) => browser.setDevicePreset(params, context.browserTarget) });
  catalogue.register({ name: 'antifan_list_device_presets', description: 'Alias for browser.list-device-presets', risk: 'read', inputSchema: { type: 'object' }, execute: () => browser.listDevicePresets() });
  catalogue.register({ name: 'antifan_set_zoom', description: 'Alias for browser.set-zoom', risk: 'write', inputSchema: { type: 'object', properties: { zoomFactor: { type: 'number', minimum: 0.25, maximum: 5.0, description: 'Zoom factor between 0.25 and 5.0' }, tabId: { type: 'string' } }, required: ['zoomFactor'] }, execute: (params: { zoomFactor: number; tabId?: string }, context) => browser.setZoom(params, context.browserTarget) });
}

export function legacyContext(target: BrowserTarget, lease: CapabilityRequestContext['lease']): CapabilityRequestContext {
  return { lease, leaseToken: lease.token, projectId: target.projectId, workspaceId: target.workspaceId, browserTarget: target, grant: 'read' };
}
